# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "honomara"
  end

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  config.vm.synced_folder "../", "/vagrant"

  config.vm.provision "shell", inline: <<-SHELL
    export LC_ALL=C.UTF-8
    echo "export LC_ALL=C.UTF-8" >> /home/vagrant/.bashrc
    sudo apt update -y
    echo grub-pc hold | dpkg --set-selections
    sudo apt upgrade -y
  SHELL

end
