# -*- mode: ruby -*-
# vi: set ft=ruby :
require "rbconfig"

def os
  @os ||= (host_os = RbConfig::CONFIG["host_os"]
    case host_os
  when /mswin|msys|mingw|cygwin|bccwin|wince|emc/
    :windows
  when /darwin|mac os/
    :macosx
  when /linux/
    :linux
  when /solaris|bsd/
    :unix
  else
    :unknown
  end)
end

Vagrant.configure("2") do |config|
  config.vm.define :default, primary: true do |machine|
    if os == :linux
      machine.vm.box = "generic/ubuntu1604"
      machine.vm.synced_folder "../", "/vagrant", type: "nfs"
      else
      machine.vm.box = "bento/ubuntu-16.04"
      machine.vm.synced_folder "../", "/vagrant"
    end

    machine.vm.network "forwarded_port", guest: 80, host: 8080 # for apache2
    machine.vm.network "forwarded_port", guest: 9999, host: 9999 # for jupyter notebook
    machine.vm.network "forwarded_port", guest: 5000, host: 5000 # for python3 app.py
    machine.vm.network "forwarded_port", guest: 3306, host: 3306 # for mysql

    machine.vm.provision "shell", inline: <<-SHELL
      sudo sed -i.bak -e "s%http://us.archive.ubuntu.com/ubuntu/%http://ftp.iij.ad.jp/pub/linux/ubuntu/archive/%g" /etc/apt/sources.list
      echo "export LC_ALL=C.UTF-8" >> /home/vagrant/.bashrc
      sudo apt update -y
      echo grub-pc hold | dpkg --set-selections
      sudo apt upgrade -y
    SHELL
  end

  config.vm.define :centos, autostart: false do |machine|
    machine.vm.box = "centos/8"
    if os == :linux
      machine.vm.synced_folder "../", "/vagrant", type: "nfs"
      else
      machine.vm.synced_folder "../", "/vagrant"
    end

    machine.vm.network "forwarded_port", guest: 80, host: 8081 # for apache2
    machine.vm.network "forwarded_port", guest: 9999, host: 10000 # for jupyter notebook
    machine.vm.network "forwarded_port", guest: 5000, host: 5001 # for python3 app.py
    machine.vm.network "forwarded_port", guest: 3306, host: 3307 # for mysql

    machine.vm.provision "shell", inline: <<-SHELL
    set -eux
    export LC_ALL=C
    sudo setenforce 0
    sudo perl -i.bak -pe 's/^(\s+SELINUX=enforcing)/#$1/' /etc/selinux/config

    timedatectl set-timezone Asia/Tokyo
    SHELL
  end
end
