ALTER TABLE after_participant    ADD CONSTRAINT FOREIGN KEY (member_id)             REFERENCES member(id);
ALTER TABLE after_participant    ADD CONSTRAINT FOREIGN KEY (after_id)              REFERENCES after(id);
ALTER TABLE training_participant ADD CONSTRAINT FOREIGN KEY (member_id)             REFERENCES member(id);
ALTER TABLE training_participant ADD CONSTRAINT FOREIGN KEY (training_id)           REFERENCES training(id);
ALTER TABLE after                ADD CONSTRAINT FOREIGN KEY (restaurant_id)         REFERENCES restaurant(id);
ALTER TABLE races                ADD CONSTRAINT FOREIGN KEY (competition_id)        REFERENCES competitions(id);
ALTER TABLE results              ADD CONSTRAINT FOREIGN KEY (competition_id)        REFERENCES competitions(id);
ALTER TABLE results              ADD CONSTRAINT FOREIGN KEY (race_id)               REFERENCES races(id);
ALTER TABLE results              ADD CONSTRAINT FOREIGN KEY (member_id)             REFERENCES member(id);